platform :ios, '10.0'

inhibit_all_warnings!

def utils
    pod 'SwiftGen', '~> 6.1.0'
    pod 'SwiftLint', '~> 0.30.1'
end

def common_pods
    utils
    pod 'NodeKit', :git => 'https://github.com/surfstudio/NodeKit', :commit => 'b5c30f2a30ab3d047f19e5049d858cdd5c524c55'
    pod 'AlamofireImage', '~> 4.0.0-beta.1'
end

target 'IndoorNavigation' do
    use_frameworks!
    common_pods
end
